/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.corner.ccms.cop1.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-16T11:09:49.248+01:00")

@Api(value = "ConvenienceCardWebsiteRSServiceCH", description = "the ConvenienceCardWebsiteRSServiceCH API")
public interface ConvenienceCardWebsiteRSServiceCHApi {

    @ApiOperation(value = "", nickname = "accountRegistration", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Response") })
    @RequestMapping(value = "/ConvenienceCardWebsiteRSServiceCH/accountRegistration",
        method = RequestMethod.POST)
    ResponseEntity<Void> accountRegistration(@ApiParam(value = "", defaultValue = "") @Valid @RequestParam(value = "_wadl", required = false, defaultValue="") String wadl);


    @ApiOperation(value = "", nickname = "checkCardAndMsisdn", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Response") })
    @RequestMapping(value = "/ConvenienceCardWebsiteRSServiceCH/checkCardAndMsisdn",
        method = RequestMethod.POST)
    ResponseEntity<Void> checkCardAndMsisdn(@ApiParam(value = "", defaultValue = "") @Valid @RequestParam(value = "_wadl", required = false, defaultValue="") String wadl);


    @ApiOperation(value = "", nickname = "checkOTP", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Response") })
    @RequestMapping(value = "/ConvenienceCardWebsiteRSServiceCH/checkOTP",
        method = RequestMethod.POST)
    ResponseEntity<Void> checkOTP(@ApiParam(value = "", defaultValue = "") @Valid @RequestParam(value = "_wadl", required = false, defaultValue="") String wadl);


    @ApiOperation(value = "", nickname = "getConvenienceCardOverview", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Response") })
    @RequestMapping(value = "/ConvenienceCardWebsiteRSServiceCH/getConvenienceCardOverview",
        method = RequestMethod.GET)
    ResponseEntity<Void> getConvenienceCardOverview(@ApiParam(value = "", defaultValue = "") @Valid @RequestParam(value = "userId", required = false, defaultValue="") String userId);


    @ApiOperation(value = "", nickname = "getProfile", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Response") })
    @RequestMapping(value = "/ConvenienceCardWebsiteRSServiceCH/profile",
        method = RequestMethod.GET)
    ResponseEntity<Void> getProfile(@ApiParam(value = "", defaultValue = "") @Valid @RequestParam(value = "userId", required = false, defaultValue="") String userId);

}
