/*
 * WS2I45
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-23 16:18:44.785
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ExceptionInteroperabilityPropertyBlock
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-08T15:22:33.923Z")
public class ExceptionInteroperabilityPropertyBlock {
  @SerializedName("responseException")
  private Integer responseException = null;

  @SerializedName("responseExceptionMessage")
  private String responseExceptionMessage = null;

  @SerializedName("responseExceptionAdditionalData")
  private String responseExceptionAdditionalData = null;

  public ExceptionInteroperabilityPropertyBlock responseException(Integer responseException) {
    this.responseException = responseException;
    return this;
  }

   /**
   * Get responseException
   * @return responseException
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getResponseException() {
    return responseException;
  }

  public void setResponseException(Integer responseException) {
    this.responseException = responseException;
  }

  public ExceptionInteroperabilityPropertyBlock responseExceptionMessage(String responseExceptionMessage) {
    this.responseExceptionMessage = responseExceptionMessage;
    return this;
  }

   /**
   * Get responseExceptionMessage
   * @return responseExceptionMessage
  **/
  @ApiModelProperty(value = "")
  public String getResponseExceptionMessage() {
    return responseExceptionMessage;
  }

  public void setResponseExceptionMessage(String responseExceptionMessage) {
    this.responseExceptionMessage = responseExceptionMessage;
  }

  public ExceptionInteroperabilityPropertyBlock responseExceptionAdditionalData(String responseExceptionAdditionalData) {
    this.responseExceptionAdditionalData = responseExceptionAdditionalData;
    return this;
  }

   /**
   * Get responseExceptionAdditionalData
   * @return responseExceptionAdditionalData
  **/
  @ApiModelProperty(value = "")
  public String getResponseExceptionAdditionalData() {
    return responseExceptionAdditionalData;
  }

  public void setResponseExceptionAdditionalData(String responseExceptionAdditionalData) {
    this.responseExceptionAdditionalData = responseExceptionAdditionalData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExceptionInteroperabilityPropertyBlock exceptionInteroperabilityPropertyBlock = (ExceptionInteroperabilityPropertyBlock) o;
    return Objects.equals(this.responseException, exceptionInteroperabilityPropertyBlock.responseException) &&
        Objects.equals(this.responseExceptionMessage, exceptionInteroperabilityPropertyBlock.responseExceptionMessage) &&
        Objects.equals(this.responseExceptionAdditionalData, exceptionInteroperabilityPropertyBlock.responseExceptionAdditionalData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseException, responseExceptionMessage, responseExceptionAdditionalData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExceptionInteroperabilityPropertyBlock {\n");
    
    sb.append("    responseException: ").append(toIndentedString(responseException)).append("\n");
    sb.append("    responseExceptionMessage: ").append(toIndentedString(responseExceptionMessage)).append("\n");
    sb.append("    responseExceptionAdditionalData: ").append(toIndentedString(responseExceptionAdditionalData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

