/*
 * WS2I45
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-23 16:18:44.785
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * RequestBodyPersonRatings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-08T15:22:33.923Z")
public class RequestBodyPersonRatings {
  @SerializedName("crifConsumerScore")
  private BigDecimal crifConsumerScore = null;

  @SerializedName("crifConsumerScoreLevel")
  private String crifConsumerScoreLevel = null;

  @SerializedName("deoRating")
  private String deoRating = null;

  @SerializedName("zekikoRating")
  private String zekikoRating = null;

  @SerializedName("zekTotalDebitAmount")
  private BigDecimal zekTotalDebitAmount = null;

  @SerializedName("zekTotalDebitCurrency")
  private String zekTotalDebitCurrency = null;

  @SerializedName("zekMonthlyDebitAmount")
  private BigDecimal zekMonthlyDebitAmount = null;

  @SerializedName("zekMonthlyDebitCurrency")
  private String zekMonthlyDebitCurrency = null;

  @SerializedName("behaviouralScore")
  private String behaviouralScore = null;

  @SerializedName("behavouralScoreLevel")
  private String behavouralScoreLevel = null;

  @SerializedName("creditWorthinessAmount")
  private BigDecimal creditWorthinessAmount = null;

  @SerializedName("creditWorthinessCurrency")
  private String creditWorthinessCurrency = null;

  public RequestBodyPersonRatings crifConsumerScore(BigDecimal crifConsumerScore) {
    this.crifConsumerScore = crifConsumerScore;
    return this;
  }

   /**
   * Get crifConsumerScore
   * @return crifConsumerScore
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getCrifConsumerScore() {
    return crifConsumerScore;
  }

  public void setCrifConsumerScore(BigDecimal crifConsumerScore) {
    this.crifConsumerScore = crifConsumerScore;
  }

  public RequestBodyPersonRatings crifConsumerScoreLevel(String crifConsumerScoreLevel) {
    this.crifConsumerScoreLevel = crifConsumerScoreLevel;
    return this;
  }

   /**
   * Get crifConsumerScoreLevel
   * @return crifConsumerScoreLevel
  **/
  @ApiModelProperty(value = "")
  public String getCrifConsumerScoreLevel() {
    return crifConsumerScoreLevel;
  }

  public void setCrifConsumerScoreLevel(String crifConsumerScoreLevel) {
    this.crifConsumerScoreLevel = crifConsumerScoreLevel;
  }

  public RequestBodyPersonRatings deoRating(String deoRating) {
    this.deoRating = deoRating;
    return this;
  }

   /**
   * Get deoRating
   * @return deoRating
  **/
  @ApiModelProperty(value = "")
  public String getDeoRating() {
    return deoRating;
  }

  public void setDeoRating(String deoRating) {
    this.deoRating = deoRating;
  }

  public RequestBodyPersonRatings zekikoRating(String zekikoRating) {
    this.zekikoRating = zekikoRating;
    return this;
  }

   /**
   * Get zekikoRating
   * @return zekikoRating
  **/
  @ApiModelProperty(value = "")
  public String getZekikoRating() {
    return zekikoRating;
  }

  public void setZekikoRating(String zekikoRating) {
    this.zekikoRating = zekikoRating;
  }

  public RequestBodyPersonRatings zekTotalDebitAmount(BigDecimal zekTotalDebitAmount) {
    this.zekTotalDebitAmount = zekTotalDebitAmount;
    return this;
  }

   /**
   * Get zekTotalDebitAmount
   * @return zekTotalDebitAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getZekTotalDebitAmount() {
    return zekTotalDebitAmount;
  }

  public void setZekTotalDebitAmount(BigDecimal zekTotalDebitAmount) {
    this.zekTotalDebitAmount = zekTotalDebitAmount;
  }

  public RequestBodyPersonRatings zekTotalDebitCurrency(String zekTotalDebitCurrency) {
    this.zekTotalDebitCurrency = zekTotalDebitCurrency;
    return this;
  }

   /**
   * Get zekTotalDebitCurrency
   * @return zekTotalDebitCurrency
  **/
  @ApiModelProperty(value = "")
  public String getZekTotalDebitCurrency() {
    return zekTotalDebitCurrency;
  }

  public void setZekTotalDebitCurrency(String zekTotalDebitCurrency) {
    this.zekTotalDebitCurrency = zekTotalDebitCurrency;
  }

  public RequestBodyPersonRatings zekMonthlyDebitAmount(BigDecimal zekMonthlyDebitAmount) {
    this.zekMonthlyDebitAmount = zekMonthlyDebitAmount;
    return this;
  }

   /**
   * Get zekMonthlyDebitAmount
   * @return zekMonthlyDebitAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getZekMonthlyDebitAmount() {
    return zekMonthlyDebitAmount;
  }

  public void setZekMonthlyDebitAmount(BigDecimal zekMonthlyDebitAmount) {
    this.zekMonthlyDebitAmount = zekMonthlyDebitAmount;
  }

  public RequestBodyPersonRatings zekMonthlyDebitCurrency(String zekMonthlyDebitCurrency) {
    this.zekMonthlyDebitCurrency = zekMonthlyDebitCurrency;
    return this;
  }

   /**
   * Get zekMonthlyDebitCurrency
   * @return zekMonthlyDebitCurrency
  **/
  @ApiModelProperty(value = "")
  public String getZekMonthlyDebitCurrency() {
    return zekMonthlyDebitCurrency;
  }

  public void setZekMonthlyDebitCurrency(String zekMonthlyDebitCurrency) {
    this.zekMonthlyDebitCurrency = zekMonthlyDebitCurrency;
  }

  public RequestBodyPersonRatings behaviouralScore(String behaviouralScore) {
    this.behaviouralScore = behaviouralScore;
    return this;
  }

   /**
   * Get behaviouralScore
   * @return behaviouralScore
  **/
  @ApiModelProperty(value = "")
  public String getBehaviouralScore() {
    return behaviouralScore;
  }

  public void setBehaviouralScore(String behaviouralScore) {
    this.behaviouralScore = behaviouralScore;
  }

  public RequestBodyPersonRatings behavouralScoreLevel(String behavouralScoreLevel) {
    this.behavouralScoreLevel = behavouralScoreLevel;
    return this;
  }

   /**
   * Get behavouralScoreLevel
   * @return behavouralScoreLevel
  **/
  @ApiModelProperty(value = "")
  public String getBehavouralScoreLevel() {
    return behavouralScoreLevel;
  }

  public void setBehavouralScoreLevel(String behavouralScoreLevel) {
    this.behavouralScoreLevel = behavouralScoreLevel;
  }

  public RequestBodyPersonRatings creditWorthinessAmount(BigDecimal creditWorthinessAmount) {
    this.creditWorthinessAmount = creditWorthinessAmount;
    return this;
  }

   /**
   * Get creditWorthinessAmount
   * @return creditWorthinessAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getCreditWorthinessAmount() {
    return creditWorthinessAmount;
  }

  public void setCreditWorthinessAmount(BigDecimal creditWorthinessAmount) {
    this.creditWorthinessAmount = creditWorthinessAmount;
  }

  public RequestBodyPersonRatings creditWorthinessCurrency(String creditWorthinessCurrency) {
    this.creditWorthinessCurrency = creditWorthinessCurrency;
    return this;
  }

   /**
   * Get creditWorthinessCurrency
   * @return creditWorthinessCurrency
  **/
  @ApiModelProperty(value = "")
  public String getCreditWorthinessCurrency() {
    return creditWorthinessCurrency;
  }

  public void setCreditWorthinessCurrency(String creditWorthinessCurrency) {
    this.creditWorthinessCurrency = creditWorthinessCurrency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestBodyPersonRatings requestBodyPersonRatings = (RequestBodyPersonRatings) o;
    return Objects.equals(this.crifConsumerScore, requestBodyPersonRatings.crifConsumerScore) &&
        Objects.equals(this.crifConsumerScoreLevel, requestBodyPersonRatings.crifConsumerScoreLevel) &&
        Objects.equals(this.deoRating, requestBodyPersonRatings.deoRating) &&
        Objects.equals(this.zekikoRating, requestBodyPersonRatings.zekikoRating) &&
        Objects.equals(this.zekTotalDebitAmount, requestBodyPersonRatings.zekTotalDebitAmount) &&
        Objects.equals(this.zekTotalDebitCurrency, requestBodyPersonRatings.zekTotalDebitCurrency) &&
        Objects.equals(this.zekMonthlyDebitAmount, requestBodyPersonRatings.zekMonthlyDebitAmount) &&
        Objects.equals(this.zekMonthlyDebitCurrency, requestBodyPersonRatings.zekMonthlyDebitCurrency) &&
        Objects.equals(this.behaviouralScore, requestBodyPersonRatings.behaviouralScore) &&
        Objects.equals(this.behavouralScoreLevel, requestBodyPersonRatings.behavouralScoreLevel) &&
        Objects.equals(this.creditWorthinessAmount, requestBodyPersonRatings.creditWorthinessAmount) &&
        Objects.equals(this.creditWorthinessCurrency, requestBodyPersonRatings.creditWorthinessCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(crifConsumerScore, crifConsumerScoreLevel, deoRating, zekikoRating, zekTotalDebitAmount, zekTotalDebitCurrency, zekMonthlyDebitAmount, zekMonthlyDebitCurrency, behaviouralScore, behavouralScoreLevel, creditWorthinessAmount, creditWorthinessCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestBodyPersonRatings {\n");
    
    sb.append("    crifConsumerScore: ").append(toIndentedString(crifConsumerScore)).append("\n");
    sb.append("    crifConsumerScoreLevel: ").append(toIndentedString(crifConsumerScoreLevel)).append("\n");
    sb.append("    deoRating: ").append(toIndentedString(deoRating)).append("\n");
    sb.append("    zekikoRating: ").append(toIndentedString(zekikoRating)).append("\n");
    sb.append("    zekTotalDebitAmount: ").append(toIndentedString(zekTotalDebitAmount)).append("\n");
    sb.append("    zekTotalDebitCurrency: ").append(toIndentedString(zekTotalDebitCurrency)).append("\n");
    sb.append("    zekMonthlyDebitAmount: ").append(toIndentedString(zekMonthlyDebitAmount)).append("\n");
    sb.append("    zekMonthlyDebitCurrency: ").append(toIndentedString(zekMonthlyDebitCurrency)).append("\n");
    sb.append("    behaviouralScore: ").append(toIndentedString(behaviouralScore)).append("\n");
    sb.append("    behavouralScoreLevel: ").append(toIndentedString(behavouralScoreLevel)).append("\n");
    sb.append("    creditWorthinessAmount: ").append(toIndentedString(creditWorthinessAmount)).append("\n");
    sb.append("    creditWorthinessCurrency: ").append(toIndentedString(creditWorthinessCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

