/*
 * WS2I45
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-23 16:18:44.785
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * RequestBodyDecisionsCalculatedLiabilities
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-08T15:22:33.923Z")
public class RequestBodyDecisionsCalculatedLiabilities {
  @SerializedName("maximumCalculatedAmount")
  private BigDecimal maximumCalculatedAmount = null;

  @SerializedName("maximumCalculatedCurrency")
  private String maximumCalculatedCurrency = null;

  @SerializedName("maximumConsumerFinanceAmount")
  private BigDecimal maximumConsumerFinanceAmount = null;

  @SerializedName("maximumConsumerFinanceCurrency")
  private String maximumConsumerFinanceCurrency = null;

  @SerializedName("maximumTemporaryAmount")
  private BigDecimal maximumTemporaryAmount = null;

  @SerializedName("maximumTemporaryCurrency")
  private String maximumTemporaryCurrency = null;

  public RequestBodyDecisionsCalculatedLiabilities maximumCalculatedAmount(BigDecimal maximumCalculatedAmount) {
    this.maximumCalculatedAmount = maximumCalculatedAmount;
    return this;
  }

   /**
   * Get maximumCalculatedAmount
   * @return maximumCalculatedAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMaximumCalculatedAmount() {
    return maximumCalculatedAmount;
  }

  public void setMaximumCalculatedAmount(BigDecimal maximumCalculatedAmount) {
    this.maximumCalculatedAmount = maximumCalculatedAmount;
  }

  public RequestBodyDecisionsCalculatedLiabilities maximumCalculatedCurrency(String maximumCalculatedCurrency) {
    this.maximumCalculatedCurrency = maximumCalculatedCurrency;
    return this;
  }

   /**
   * Get maximumCalculatedCurrency
   * @return maximumCalculatedCurrency
  **/
  @ApiModelProperty(value = "")
  public String getMaximumCalculatedCurrency() {
    return maximumCalculatedCurrency;
  }

  public void setMaximumCalculatedCurrency(String maximumCalculatedCurrency) {
    this.maximumCalculatedCurrency = maximumCalculatedCurrency;
  }

  public RequestBodyDecisionsCalculatedLiabilities maximumConsumerFinanceAmount(BigDecimal maximumConsumerFinanceAmount) {
    this.maximumConsumerFinanceAmount = maximumConsumerFinanceAmount;
    return this;
  }

   /**
   * Get maximumConsumerFinanceAmount
   * @return maximumConsumerFinanceAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMaximumConsumerFinanceAmount() {
    return maximumConsumerFinanceAmount;
  }

  public void setMaximumConsumerFinanceAmount(BigDecimal maximumConsumerFinanceAmount) {
    this.maximumConsumerFinanceAmount = maximumConsumerFinanceAmount;
  }

  public RequestBodyDecisionsCalculatedLiabilities maximumConsumerFinanceCurrency(String maximumConsumerFinanceCurrency) {
    this.maximumConsumerFinanceCurrency = maximumConsumerFinanceCurrency;
    return this;
  }

   /**
   * Get maximumConsumerFinanceCurrency
   * @return maximumConsumerFinanceCurrency
  **/
  @ApiModelProperty(value = "")
  public String getMaximumConsumerFinanceCurrency() {
    return maximumConsumerFinanceCurrency;
  }

  public void setMaximumConsumerFinanceCurrency(String maximumConsumerFinanceCurrency) {
    this.maximumConsumerFinanceCurrency = maximumConsumerFinanceCurrency;
  }

  public RequestBodyDecisionsCalculatedLiabilities maximumTemporaryAmount(BigDecimal maximumTemporaryAmount) {
    this.maximumTemporaryAmount = maximumTemporaryAmount;
    return this;
  }

   /**
   * Get maximumTemporaryAmount
   * @return maximumTemporaryAmount
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getMaximumTemporaryAmount() {
    return maximumTemporaryAmount;
  }

  public void setMaximumTemporaryAmount(BigDecimal maximumTemporaryAmount) {
    this.maximumTemporaryAmount = maximumTemporaryAmount;
  }

  public RequestBodyDecisionsCalculatedLiabilities maximumTemporaryCurrency(String maximumTemporaryCurrency) {
    this.maximumTemporaryCurrency = maximumTemporaryCurrency;
    return this;
  }

   /**
   * Get maximumTemporaryCurrency
   * @return maximumTemporaryCurrency
  **/
  @ApiModelProperty(value = "")
  public String getMaximumTemporaryCurrency() {
    return maximumTemporaryCurrency;
  }

  public void setMaximumTemporaryCurrency(String maximumTemporaryCurrency) {
    this.maximumTemporaryCurrency = maximumTemporaryCurrency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestBodyDecisionsCalculatedLiabilities requestBodyDecisionsCalculatedLiabilities = (RequestBodyDecisionsCalculatedLiabilities) o;
    return Objects.equals(this.maximumCalculatedAmount, requestBodyDecisionsCalculatedLiabilities.maximumCalculatedAmount) &&
        Objects.equals(this.maximumCalculatedCurrency, requestBodyDecisionsCalculatedLiabilities.maximumCalculatedCurrency) &&
        Objects.equals(this.maximumConsumerFinanceAmount, requestBodyDecisionsCalculatedLiabilities.maximumConsumerFinanceAmount) &&
        Objects.equals(this.maximumConsumerFinanceCurrency, requestBodyDecisionsCalculatedLiabilities.maximumConsumerFinanceCurrency) &&
        Objects.equals(this.maximumTemporaryAmount, requestBodyDecisionsCalculatedLiabilities.maximumTemporaryAmount) &&
        Objects.equals(this.maximumTemporaryCurrency, requestBodyDecisionsCalculatedLiabilities.maximumTemporaryCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maximumCalculatedAmount, maximumCalculatedCurrency, maximumConsumerFinanceAmount, maximumConsumerFinanceCurrency, maximumTemporaryAmount, maximumTemporaryCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestBodyDecisionsCalculatedLiabilities {\n");
    
    sb.append("    maximumCalculatedAmount: ").append(toIndentedString(maximumCalculatedAmount)).append("\n");
    sb.append("    maximumCalculatedCurrency: ").append(toIndentedString(maximumCalculatedCurrency)).append("\n");
    sb.append("    maximumConsumerFinanceAmount: ").append(toIndentedString(maximumConsumerFinanceAmount)).append("\n");
    sb.append("    maximumConsumerFinanceCurrency: ").append(toIndentedString(maximumConsumerFinanceCurrency)).append("\n");
    sb.append("    maximumTemporaryAmount: ").append(toIndentedString(maximumTemporaryAmount)).append("\n");
    sb.append("    maximumTemporaryCurrency: ").append(toIndentedString(maximumTemporaryCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

