/*
 * WS2I45
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-23 16:18:44.785
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ExceptionInteroperabilityPropertyBlocks;
import io.swagger.client.model.HeaderResponse;
import io.swagger.client.model.ResponseInteroperabilityPropertyBlock;
import java.io.IOException;

/**
 * Response Body
 */
@ApiModel(description = "Response Body")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-08T15:22:33.923Z")
public class ResponseBody {
  @SerializedName("headerResponse")
  private HeaderResponse headerResponse = null;

  @SerializedName("responseInteroperabilityPropertyBlock")
  private ResponseInteroperabilityPropertyBlock responseInteroperabilityPropertyBlock = null;

  @SerializedName("exceptionInteroperabilityPropertyBlocks")
  private ExceptionInteroperabilityPropertyBlocks exceptionInteroperabilityPropertyBlocks = null;

  public ResponseBody headerResponse(HeaderResponse headerResponse) {
    this.headerResponse = headerResponse;
    return this;
  }

   /**
   * Get headerResponse
   * @return headerResponse
  **/
  @ApiModelProperty(required = true, value = "")
  public HeaderResponse getHeaderResponse() {
    return headerResponse;
  }

  public void setHeaderResponse(HeaderResponse headerResponse) {
    this.headerResponse = headerResponse;
  }

  public ResponseBody responseInteroperabilityPropertyBlock(ResponseInteroperabilityPropertyBlock responseInteroperabilityPropertyBlock) {
    this.responseInteroperabilityPropertyBlock = responseInteroperabilityPropertyBlock;
    return this;
  }

   /**
   * Get responseInteroperabilityPropertyBlock
   * @return responseInteroperabilityPropertyBlock
  **/
  @ApiModelProperty(required = true, value = "")
  public ResponseInteroperabilityPropertyBlock getResponseInteroperabilityPropertyBlock() {
    return responseInteroperabilityPropertyBlock;
  }

  public void setResponseInteroperabilityPropertyBlock(ResponseInteroperabilityPropertyBlock responseInteroperabilityPropertyBlock) {
    this.responseInteroperabilityPropertyBlock = responseInteroperabilityPropertyBlock;
  }

  public ResponseBody exceptionInteroperabilityPropertyBlocks(ExceptionInteroperabilityPropertyBlocks exceptionInteroperabilityPropertyBlocks) {
    this.exceptionInteroperabilityPropertyBlocks = exceptionInteroperabilityPropertyBlocks;
    return this;
  }

   /**
   * Get exceptionInteroperabilityPropertyBlocks
   * @return exceptionInteroperabilityPropertyBlocks
  **/
  @ApiModelProperty(value = "")
  public ExceptionInteroperabilityPropertyBlocks getExceptionInteroperabilityPropertyBlocks() {
    return exceptionInteroperabilityPropertyBlocks;
  }

  public void setExceptionInteroperabilityPropertyBlocks(ExceptionInteroperabilityPropertyBlocks exceptionInteroperabilityPropertyBlocks) {
    this.exceptionInteroperabilityPropertyBlocks = exceptionInteroperabilityPropertyBlocks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseBody responseBody = (ResponseBody) o;
    return Objects.equals(this.headerResponse, responseBody.headerResponse) &&
        Objects.equals(this.responseInteroperabilityPropertyBlock, responseBody.responseInteroperabilityPropertyBlock) &&
        Objects.equals(this.exceptionInteroperabilityPropertyBlocks, responseBody.exceptionInteroperabilityPropertyBlocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headerResponse, responseInteroperabilityPropertyBlock, exceptionInteroperabilityPropertyBlocks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseBody {\n");
    
    sb.append("    headerResponse: ").append(toIndentedString(headerResponse)).append("\n");
    sb.append("    responseInteroperabilityPropertyBlock: ").append(toIndentedString(responseInteroperabilityPropertyBlock)).append("\n");
    sb.append("    exceptionInteroperabilityPropertyBlocks: ").append(toIndentedString(exceptionInteroperabilityPropertyBlocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

