/*
 * WS2I45
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-23 16:18:44.785
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SortingSortBlock;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Sorting
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-08T15:22:33.923Z")
public class Sorting {
  @SerializedName("sortBlock")
  private List<SortingSortBlock> sortBlock = new ArrayList<SortingSortBlock>();

  public Sorting sortBlock(List<SortingSortBlock> sortBlock) {
    this.sortBlock = sortBlock;
    return this;
  }

  public Sorting addSortBlockItem(SortingSortBlock sortBlockItem) {
    this.sortBlock.add(sortBlockItem);
    return this;
  }

   /**
   * Get sortBlock
   * @return sortBlock
  **/
  @ApiModelProperty(required = true, value = "")
  public List<SortingSortBlock> getSortBlock() {
    return sortBlock;
  }

  public void setSortBlock(List<SortingSortBlock> sortBlock) {
    this.sortBlock = sortBlock;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sorting sorting = (Sorting) o;
    return Objects.equals(this.sortBlock, sorting.sortBlock);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sortBlock);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sorting {\n");
    
    sb.append("    sortBlock: ").append(toIndentedString(sortBlock)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

