/*
 * WS2I45
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-23 16:18:44.785
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SortingSortAttribute;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SortingSortBlock
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-12-08T15:22:33.923Z")
public class SortingSortBlock {
  @SerializedName("name")
  private String name = null;

  @SerializedName("sortAttribute")
  private List<SortingSortAttribute> sortAttribute = new ArrayList<SortingSortAttribute>();

  public SortingSortBlock name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SortingSortBlock sortAttribute(List<SortingSortAttribute> sortAttribute) {
    this.sortAttribute = sortAttribute;
    return this;
  }

  public SortingSortBlock addSortAttributeItem(SortingSortAttribute sortAttributeItem) {
    this.sortAttribute.add(sortAttributeItem);
    return this;
  }

   /**
   * Get sortAttribute
   * @return sortAttribute
  **/
  @ApiModelProperty(required = true, value = "")
  public List<SortingSortAttribute> getSortAttribute() {
    return sortAttribute;
  }

  public void setSortAttribute(List<SortingSortAttribute> sortAttribute) {
    this.sortAttribute = sortAttribute;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SortingSortBlock sortingSortBlock = (SortingSortBlock) o;
    return Objects.equals(this.name, sortingSortBlock.name) &&
        Objects.equals(this.sortAttribute, sortingSortBlock.sortAttribute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, sortAttribute);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SortingSortBlock {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sortAttribute: ").append(toIndentedString(sortAttribute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

