/*
 * WS2I45
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-23 16:18:44.785
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ExceptionResponseBody;
import io.swagger.client.model.RequestBody;
import io.swagger.client.model.ResponseBody;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Ws2I45Api
 */
@Ignore
public class Ws2I45ApiTest {

    private final Ws2I45Api api = new Ws2I45Api();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void wS2I45Test() throws ApiException {
        RequestBody requestBody = null;
        ResponseBody response = api.wS2I45(requestBody);

        // TODO: test validations
    }
    
}
